### ISSUE TITLE
missing a license

### ISSUE THREAD

**Issue by divinity76** [haibbo/speedtest-cli#9]
ILIKEANAL but you should probably add a license, 

if you want people to do whatever they want, even using the code without crediting you, then maybe the [CC0](https://choosealicense.com/licenses/cc0-1.0/) is a good fit

if you want people to give you credit for using your code, but be otherwise free to do whatever they want, i suggest the [MIT](https://choosealicense.com/licenses/mit/) license

or if you just hate licenses and want to tell people that they're free to do whatever they want, maybe try the [WTFPL](https://choosealicense.com/licenses/unlicense/) license

(i have mostly been using the "[The Unlicense](https://choosealicense.com/licenses/unlicense/)" myself, but many people smarter than myself says that the CC0 license makes "The Unlicense" obsolete, and CC0 should always be used instead of Unlicense, but idk.)

**Comment by haibbo** [comment]
Add a MIT license
